### ISSUE TITLE
Virus warning on Windows

### ISSUE THREAD

**Issue by stianhoiland** [JacksonAllan/CC#2]
Downloading CC-main.zip and extracting with 7zip, 7zip says: "Operation did not complete successfully because the file contains a virus of potentially unwanted software."
Windows Defender/Security blocks and reports threat as "Trojan:Script/Wacatac.H!ml"

https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Script/Wacatac.H!ml&threatid=2147814524

![CC-main.zip virus warning](https://user-images.githubusercontent.com/2081712/215325034-5f6cff08-45e2-4420-8e5a-2f91e83f9075.PNG)

Edition		Windows 10 Home
Version		21H2
Installed on	‎29.‎06.‎2022
OS build		19044.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by JacksonAllan** [comment]
Thanks for letting me know!

I tested on Windows 11 and got the same result. But I'm having trouble replicating the problem because after Windows flagged the file once, it refused to re-download it. And once I specified that the file is safe so that I _could_ re-download it, Windows stopped scanning it altogether.

I can see other Github projects have experienced similar problems with false positives. What's interesting is that this particular repository contains no binaries, just text. I'll have to explore the issue more. It appears that I may be able to submit the file to Microsoft to be manually checked and flagged as safe in the next update to antivirus definitions.

In the meantime, all you need to use the library is [cc.h](https://raw.githubusercontent.com/JacksonAllan/CC/main/cc.h). Optionally, you can grab [unit_tests.c](https://raw.githubusercontent.com/JacksonAllan/CC/main/tests/unit_tests.c) and [tests_against_stl.cpp](https://raw.githubusercontent.com/JacksonAllan/CC/main/tests/tests_against_stl.cpp) too. The other files in the repository are just stuff related to presentation on Github.

Alternatively, the zip files associated with the [releases](https://github.com/JacksonAllan/CC/releases/tag/v1.0.1) don't seem to be triggering Windows security.
